# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=0.1.0
maven_group=xyz.uninenville.turfwars

# Dependencies
fabric_api_version=0.161.0+26.3
plasmid_version=0.7.3-SNAPSHOT+26.3

puppet_players_version=2.1.0+26.3
fabric_language_kotlin_version=1.14.1+kotlin.2.4.20