# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.17.3
loom_version=1.13-SNAPSHOT

# Mod Properties
mod_version=0.1.0
maven_group=xyz.uninenville.turfwars
archives_base_name=turfwars

# Dependencies
fabric_version=0.138.0+1.21.10
plasmid_version=0.6.7-SNAPSHOT+1.21.10
placeholder_api_version=2.8.1+1.21.10
fabric_permission_api_version=0.5.0

carpet_core_version=1.21.10-1.4.188+v251016